name: .Simple
description: Токен приложения для учета доходов и расходов .Simple
image: "https://telega.tech/simple/icon.png"
address: EQDkMLKoahdecAEhRbDW5LvXWAoPkiIPTLnVyQRmaQ8buH25
symbol: .Simple
social:
  - "https://t.me/app_simple"