name: BUILD
description: Utility token for Telegram toolset
image: https://cdn.joincommunity.xyz/build/build_logo.png
address: EQBYnUrIlwBrWqp_rl-VxeSBvTR2VmTfC4ManQ657n_BUILD
symbol: BUILD
websites:
  - "https://openbuilders.xyz/"
social:
  - "https://t.me/join_community"
