name: Likes & Dislikes
symbol: LID
description: >
  Likes & Dislikes (LID) — токен сообщества, отражающий мнение пользователей.
  Голосуй лайком или дизлайком, формируя децентрализованный рейтинг в TON.
image: https://your-domain.com/lid-logo.png
address: EQAny4ehvsQnFPjvAAb4Fd1F638PjxJM-gtouKWIX3iG0ggZ
decimals: 9
websites: []
social:
  - https://t.me/Likes_and_Dislikes
  - https://x.com/like_an_dislike?s=21