name: CASA
symbol: CASA
decimals: 9
description: CASA Token – utility token of the Casafond ecosystem on TON.
image: logo.png
address: EQBWK_VVEBJWiIQIIXOckUVw0HdF24buJiNiiR0dUHEe2xs4
social:
  - website: https://casafond.org
  - telegram: https://t.me/casafond
