name: Test source files for correctness
on:
  pull_request:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  source-syntax-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Check that source dirs contain only *.yaml files
        run: |
          # Behold bash power and tremble!
          shopt -s extglob
          shopt -s nullglob
          for FILENAME in {accounts,collections,jettons}/!(*.yaml); do
            [ "${FILENAME}" == 'jettons/example.yaml.template' ] && continue
            echo "Found '${FILENAME}' file but only *.yaml files are allowed here."
            exit 1
          done

      - name: Dummy run of generator to check for correct syntax
        run: python3 generator.py
